### PR TITLE
State Mutation In Getter detector

### LINKED ISSUE #248: State-Mutating Function is Called in Getter
Misti should highlight these cases because they may lead to unexpected control flow.

### PR DESCRIPTION
**Pull request by Esorat**
Closes #248 

- [x] I have updated `CHANGELOG.md`
- [x] I have added tests to demonstrate the contribution is correctly implemented
- [x] No test failures were reported when running `yarn test-all`
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

File: src/detectors/builtin/stateMutationInGetter.ts [hunk 1]
```diff
@@ -0,0 +1,201 @@
...
+  AstExpression,
+  idText,
+} from "@tact-lang/compiler/dist/grammar/ast";
+
+/**
+ * An optional detector that identifies cases where a state-mutating function is called within a getter method.
+ *
+ * ## Why is it bad?
+ * Getter methods are expected to be pure functions that don't modify state. When a getter
+ * modifies state (directly or by calling other functions that do), it violates this principle
```
Comment (jubnzv) [inline src/detectors/builtin/stateMutationInGetter.ts:23]: It *does not* modify the state, but that's what the developer may except.

File: src/detectors/builtin/stateMutationInGetter.ts [hunk 2]
```diff
@@ -0,0 +1,201 @@
...
+      (acc, stmt) => {
+        const mutations = collectMutations(stmt);
+        if (mutations && mutations.mutatedFields.length > 0) {
+          acc.push(
+            this.makeWarning(
+              "Getter directly mutates contract state",
+              stmt.loc,
+              {
+                extraDescription:
+                  "Getter methods should not modify state directly or indirectly",
```
Comment (jubnzv) [inline src/detectors/builtin/stateMutationInGetter.ts:125]: It does not. We need to rephrase all the warning messages to clarify that the developer might misunderstand them. That detector is intended solely for auditors to highlight these specific areas.

File: src/detectors/builtin/stateMutationInGetter.ts [hunk 3]
```diff
@@ -0,0 +1,201 @@
...
+   */
+  private checkStaticCall(
+    cu: CompilationUnit,
+    call: AstStaticCall,
+    contractName: string,
+    warnings: MistiTactWarning[],
+  ): void {
+    const calleeName = idText(call.function);
+    const calleeNodeId = cu.callGraph.getNodeIdByName(calleeName);
+
```
Comment (jubnzv) [inline src/detectors/builtin/stateMutationInGetter.ts:149]:
```suggestion
```

File: src/detectors/builtin/stateMutationInGetter.ts [hunk 4]
```diff
@@ -0,0 +1,201 @@
...
+  private checkMethodCall(
+    cu: CompilationUnit,
+    call: AstMethodCall,
+    contractName: string,
+    warnings: MistiTactWarning[],
+  ): void {
+    // For self.method() calls check the contract's method
+    if (call.self.kind === "id" && idText(call.self) === "self") {
+      const methodName = idText(call.method);
+      const fullMethodName = `${contractName}::${methodName}`;
```
Comment (jubnzv) [inline src/detectors/builtin/stateMutationInGetter.ts:180]: This is unreliable since the naming logic will be changed soon. Replace w/ a function from `callgraph.ts`.

File: src/detectors/builtin/stateMutationInGetter.ts [hunk 5]
```diff
@@ -0,0 +1,201 @@
...
+   * Checks if a method call might modify state
+   */
+  private checkMethodCall(
+    cu: CompilationUnit,
+    call: AstMethodCall,
+    contractName: string,
+    warnings: MistiTactWarning[],
+  ): void {
+    // For self.method() calls check the contract's method
+    if (call.self.kind === "id" && idText(call.self) === "self") {
```
Comment (jubnzv) [inline src/detectors/builtin/stateMutationInGetter.ts:178]: `isSelf(call.self)`

File: src/detectors/builtin/stateMutationInGetter.ts [hunk 6]
```diff
@@ -0,0 +1,201 @@
...
+ *   fun getAndIncrement(): Int {
+ *     let current = self.value;
+ *     self.value = self.value + 1;
+ *     return current;
+ *   }
+ * }
+ * ```
+ */
+export class StateMutationInGetter extends AstDetector {
+  severity = Severity.LOW;
```
Comment (jubnzv) [inline src/detectors/builtin/stateMutationInGetter.ts:61]:
```suggestion
  severity = Severity.INFO;
```

File: src/detectors/builtin/stateMutationInGetter.ts [hunk 7]
```diff
@@ -0,0 +1,201 @@
...
+
+  async check(cu: CompilationUnit): Promise<MistiTactWarning[]> {
+    const warnings: MistiTactWarning[] = [];
+
```
Comment (jubnzv) [inline src/detectors/builtin/stateMutationInGetter.ts:65]:
```suggestion
```

File: src/detectors/builtin/stateMutationInGetter.ts [hunk 8]
```diff
@@ -0,0 +1,201 @@
...
+          this.checkGetterForStateMutations(
+            cu,
+            decl,
+            contract.name.text,
+            warnings,
+          );
+        }
+      }
+    }
+
```
Comment (jubnzv) [inline src/detectors/builtin/stateMutationInGetter.ts:81]:
```suggestion
```

**Review by jubnzv — CHANGES_REQUESTED** [review]
