### PR TITLE
fix: add docstrings

### LINKED ISSUE #175: `SendInLoop`: Add docstring describing the detector
The detector should have a docstring in the following format:

https://github.com/nowarp/misti/blob/2ecd5f280576347347ee8669b7fd12a470854923/src/detectors/builtin/dumpIsUsed.ts#L8

That's important since we generate documentation hosted on nowarp.io automatically, using these docstrings.

### PR DESCRIPTION
**Pull request by Esorat**
Closes #175

- [ ] I have updated `CHANGELOG.md`
- [x] I have added tests to demonstrate the contribution is correctly implemented
- [x] No test failures were reported when running `yarn test-all`
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

File: src/detectors/builtin/sendInLoop.ts [hunk 1]
```diff
@@ -8,6 +8,52 @@ import {
...
+ * Use instead:
+ * ```tact
+ * fun refactorExample(limit: Int) {
+ *   let i = 0;
+ *   let messages: list<Msg> = [];
+ *   while (i < limit) {
+ *       messages.push(Msg{ a: i });
+ *       i += 1;
+ *   }
+ *   for (msg in messages) {
```
Comment (jubnzv) [inline src/detectors/builtin/sendInLoop.ts:45]: Could it be compiled with Tact?

Comment (Esorat) [reply src/detectors/builtin/sendInLoop.ts]: unfortunately no.

**Review by jubnzv — APPROVED** [review]
