### PR TITLE
Callgraph: Fix handling of getter methods

### LINKED ISSUE #266: Callgraph: Incorrect handling of getter methods
MRE:
```tact
contract A {
    m: map<Int, Int> = null;
    get fun m(): map<Int, Int> {
        return self.m;
    }
    receive() {
        while (true) {
            self.m.set(1, 2);
        }
    }
}
```

Creates the following mmd dump:
```mermaid
graph TD
    node_17["get fun m(): map<Int, Int>
[StateRead]"]
    node_18["receive()
[StateRead]"]
    node_19["set"]
    node_18 --> node_19
```

Which is incorrect, since `m` is a field, not a contract method.

This leads to the following warning when running `SendInLoop`:
```
Cannot retrieve CG node: A::set 
```

### PR DESCRIPTION
**Pull request by jubnzv**
Closes #266

- [x] I have updated `CHANGELOG.md`
- [x] I have added tests to demonstrate the contribution is correctly implemented
- [x] No test failures were reported when running `yarn test-all`
- [ ] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

File: src/internals/ir/callGraph.ts [hunk 1]
```diff
@@ -352,16 +349,13 @@ export class CallGraph {
...
-              | AstContractInit
-              | AstReceiver;
+            const func = declaration;
             const funcNodeId = this.astIdToNodeId.get(func.id);
             if (funcNodeId !== undefined) {
               const funcNode = this.getNode(funcNodeId);
               if (!funcNode) continue;
               func.statements.forEach((stmt) => {
-                this.processStatement(stmt, funcNodeId);
+                this.processStatement(stmt, funcNodeId, idText(contract.name));
```
Comment (jubnzv) [inline src/internals/ir/callGraph.ts:358]: This fixed name collisions between free functions and methods.

**Review by Esorat — APPROVED** [review]
LGTM!
